### ISSUE TITLE
Add note about when window.webln is available

### ISSUE THREAD

**Issue by bumi** [getAlby/webln-guide#1]
window.webln is not directly available and can only used after the page is loaded. 

there is also a PR to dispatch an event when webln is ready; https://github.com/getAlby/lightning-browser-extension/pull/853

**Comment by reneaaron** [comment]
I just created a proposal: 

https://app.gitbook.com/o/uiUeRqI074apbV0PWsyf/s/SHMrYyqxEldRs701vokD/~/diff/~/changes/sEWr6Ag0XcBu5s8Lsrs7/building-lightning-apps/getting-started

Might be worth thinking about releasing such helper functions in some reusable npm package.
